### ISSUE TITLE
Support imported interface parameters in the same package as the object

### ISSUE THREAD

**Issue by tttoad** [josharian/impl#46]
Example code:
```
package repo

type BB struct {
}

type IRepo interface {
	StramCall(r string) IRepo
}

type repo struct {
}

```
use `"r *repo" IRepo` will generate 

```
func (r *repo) StramCall(r string) repo.IRepo {
	panic("not implemented") // TODO: Implement
}
```
Expect to get
```
func (r *repo) StramCall(rR string) IRepo { // The parameter name can be rR or rr 
	panic("not implemented") // TODO: Implement
}
```
If you agree with this, I can provide a PR for this feature.

**Comment by josharian** [comment]
Yes, that seems definitely wrong.

There are two bugs here, right?

One is `repo.IRepo` instead of `IRepo`. That's one we can just fix.

The other is the collision on the name `r`. Instead of attempting to guess a better parameter name, I'd rather make all the parameters unnamed in this situation. That is, do `StramCall(string)`. Alternatively, simply detect the situation and report an error to the caller.

I'd be happy with PRs to fix these, with two caveats. (1) Please send separate PRs for separate bug fixes, with separate tests. (2) Please anticipate that I may be slow to review PRs, as in months. My time for open source work is limited, and I want to be transparent about that. Feel free to ping me on PRs to remind me of their existence.

Thanks for the excellent bug report.

**Comment by josharian** [comment]
Oops, I closed this prematurely. IIUC, the second bug (parameter naming collision) is not fixed yet.
